eureka:
  client:
    serviceUrl:
      defaultZone: http://overwatch.bjike.com:9701/eureka/
server:
  port: 8763
spring:
  application:
    name: lend-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goddess?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root

#配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


## Redis 配置
## Redis数据库索引（默认为0）

  redis:
    database: 0
## Redis服务器地址
    host: 127.0.0.1
## Redis服务器连接端口
    port: 6379
## Redis服务器连接密码（默认为空）
    password:
## 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
## 连接池中的最大空闲连接
    pool:
      max-idle: 8
## 连接池中的最小空闲连接
    pool:
      min-idle: 0
## 连接超时时间（毫秒）
    timeout: 2000